services:
  flasky:
    image: 'neksper/flasky:mysql-latest'
    ports:
      - "8000:5000"
    env_file:
      - Flasky/.env
    links:
      - mysql:dbserver
    depends_on:
      - mysql
  mysql:
    image: 'mysql:latest'
    env_file:
      - Flasky/.env-mysql
    volumes:
      - mysqldata:/var/lib/mysql
    restart: always

volumes:
  mysqldata: