"""Added default, permissions fields to Role model

Revision ID: 19961ae9d366
Revises: 981547d86931
Create Date: 2025-05-17 15:26:22.008240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19961ae9d366'
down_revision = '981547d86931'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('permissions', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_roles_default'), ['default'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_default'))
        batch_op.drop_column('permissions')
        batch_op.drop_column('default')

    # ### end Alembic commands ###
