"""Added body_html field to Post model

Revision ID: c376459dcdf4
Revises: 58e7c0043395
Create Date: 2025-05-29 14:36:28.326058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c376459dcdf4'
down_revision = '58e7c0043395'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('html_body', sa.Text(), nullable=False))
        batch_op.drop_column('body_html')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body_html', sa.TEXT(), nullable=False))
        batch_op.drop_column('html_body')

    # ### end Alembic commands ###
